//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//strei//Documents//dev//Apollon//Parser//antlr//apollon.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="apollonParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IapollonVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] apollonParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQuery([NotNull] apollonParser.QueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] apollonParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFact([NotNull] apollonParser.FactContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRule([NotNull] apollonParser.RuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstraint([NotNull] apollonParser.ConstraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHead([NotNull] apollonParser.HeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody([NotNull] apollonParser.BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.body_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBody_part([NotNull] apollonParser.Body_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] apollonParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.variable_placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_placeholder([NotNull] apollonParser.Variable_placeholderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.docu_string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocu_string([NotNull] apollonParser.Docu_stringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.docu_string_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocu_string_part([NotNull] apollonParser.Docu_string_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.docu_string_string_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocu_string_string_part([NotNull] apollonParser.Docu_string_string_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.docu"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocu([NotNull] apollonParser.DocuContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.docu_head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDocu_head([NotNull] apollonParser.Docu_headContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.naf_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNaf_literal([NotNull] apollonParser.Naf_literalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] apollonParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.atom_param_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom_param_part([NotNull] apollonParser.Atom_param_partContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.general_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneral_term([NotNull] apollonParser.General_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.inline_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInline_operation([NotNull] apollonParser.Inline_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.generating_operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerating_operation([NotNull] apollonParser.Generating_operationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.generating_operation_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerating_operation_variable([NotNull] apollonParser.Generating_operation_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.generating_operation_operant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerating_operation_operant([NotNull] apollonParser.Generating_operation_operantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.inline_operators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInline_operators([NotNull] apollonParser.Inline_operatorsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="apollonParser.generating_operators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerating_operators([NotNull] apollonParser.Generating_operatorsContext context);
}
