//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//strei//Documents//dev//Apollon//Parser//antlr//apollon.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class apollonLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, NAF=6, NEGATION=7, EQUALS=8, NOT_EQUALS=9, 
		COMMENT=10, WS=11, CLASICAL_TERM=12, VARIABLE_TERM=13, NUMBER=14;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "NAF", "NEGATION", "EQUALS", "NOT_EQUALS", 
		"COMMENT", "WS", "CLASICAL_TERM", "VARIABLE_TERM", "NUMBER"
	};


	public apollonLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public apollonLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "','", "'.'", "':-'", "'('", "')'", "'not'", "'-'", "'='", "'!='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "NAF", "NEGATION", "EQUALS", "NOT_EQUALS", 
		"COMMENT", "WS", "CLASICAL_TERM", "VARIABLE_TERM", "NUMBER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "apollon.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static apollonLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,14,86,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,1,0,1,
		0,1,1,1,1,1,2,1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,5,1,5,1,6,1,6,1,7,1,7,
		1,8,1,8,1,8,1,9,1,9,5,9,54,8,9,10,9,12,9,57,9,9,1,9,1,9,1,10,4,10,62,8,
		10,11,10,12,10,63,1,10,1,10,1,11,1,11,5,11,70,8,11,10,11,12,11,73,9,11,
		1,12,1,12,5,12,77,8,12,10,12,12,12,80,9,12,1,13,4,13,83,8,13,11,13,12,
		13,84,0,0,14,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,
		25,13,27,14,1,0,6,2,0,10,10,13,13,3,0,9,10,13,13,32,32,1,0,97,122,4,0,
		48,57,65,90,95,95,97,122,1,0,65,90,1,0,48,57,90,0,1,1,0,0,0,0,3,1,0,0,
		0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,
		0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,
		0,27,1,0,0,0,1,29,1,0,0,0,3,31,1,0,0,0,5,33,1,0,0,0,7,36,1,0,0,0,9,38,
		1,0,0,0,11,40,1,0,0,0,13,44,1,0,0,0,15,46,1,0,0,0,17,48,1,0,0,0,19,51,
		1,0,0,0,21,61,1,0,0,0,23,67,1,0,0,0,25,74,1,0,0,0,27,82,1,0,0,0,29,30,
		5,44,0,0,30,2,1,0,0,0,31,32,5,46,0,0,32,4,1,0,0,0,33,34,5,58,0,0,34,35,
		5,45,0,0,35,6,1,0,0,0,36,37,5,40,0,0,37,8,1,0,0,0,38,39,5,41,0,0,39,10,
		1,0,0,0,40,41,5,110,0,0,41,42,5,111,0,0,42,43,5,116,0,0,43,12,1,0,0,0,
		44,45,5,45,0,0,45,14,1,0,0,0,46,47,5,61,0,0,47,16,1,0,0,0,48,49,5,33,0,
		0,49,50,5,61,0,0,50,18,1,0,0,0,51,55,5,37,0,0,52,54,8,0,0,0,53,52,1,0,
		0,0,54,57,1,0,0,0,55,53,1,0,0,0,55,56,1,0,0,0,56,58,1,0,0,0,57,55,1,0,
		0,0,58,59,6,9,0,0,59,20,1,0,0,0,60,62,7,1,0,0,61,60,1,0,0,0,62,63,1,0,
		0,0,63,61,1,0,0,0,63,64,1,0,0,0,64,65,1,0,0,0,65,66,6,10,0,0,66,22,1,0,
		0,0,67,71,7,2,0,0,68,70,7,3,0,0,69,68,1,0,0,0,70,73,1,0,0,0,71,69,1,0,
		0,0,71,72,1,0,0,0,72,24,1,0,0,0,73,71,1,0,0,0,74,78,7,4,0,0,75,77,7,3,
		0,0,76,75,1,0,0,0,77,80,1,0,0,0,78,76,1,0,0,0,78,79,1,0,0,0,79,26,1,0,
		0,0,80,78,1,0,0,0,81,83,7,5,0,0,82,81,1,0,0,0,83,84,1,0,0,0,84,82,1,0,
		0,0,84,85,1,0,0,0,85,28,1,0,0,0,6,0,55,63,71,78,84,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
