//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c://Users//strei//Documents//dev//Apollon//Parser//antlr//apollon.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="apollonParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IapollonListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] apollonParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] apollonParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] apollonParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] apollonParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] apollonParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] apollonParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFact([NotNull] apollonParser.FactContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFact([NotNull] apollonParser.FactContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule([NotNull] apollonParser.RuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule([NotNull] apollonParser.RuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstraint([NotNull] apollonParser.ConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstraint([NotNull] apollonParser.ConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHead([NotNull] apollonParser.HeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHead([NotNull] apollonParser.HeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] apollonParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] apollonParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.body_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody_part([NotNull] apollonParser.Body_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.body_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody_part([NotNull] apollonParser.Body_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] apollonParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] apollonParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.naf_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNaf_literal([NotNull] apollonParser.Naf_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.naf_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNaf_literal([NotNull] apollonParser.Naf_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] apollonParser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] apollonParser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.atom_param_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom_param_part([NotNull] apollonParser.Atom_param_partContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.atom_param_part"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom_param_part([NotNull] apollonParser.Atom_param_partContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.general_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneral_term([NotNull] apollonParser.General_termContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.general_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneral_term([NotNull] apollonParser.General_termContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperation([NotNull] apollonParser.OperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperation([NotNull] apollonParser.OperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="apollonParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator([NotNull] apollonParser.OperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="apollonParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator([NotNull] apollonParser.OperatorContext context);
}
